# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '0726_Kanna03_TableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 0726_Kanna03_TableView
pod 'Kanna','~>5.0.0'

end
